title: "JHU Modern Cryptography '26"
schedule:
    - date: "Jan 20"
      topic: "Introduction and Prerequisites"
      slides: "[PDF](slides/lec_0.pdf)"
      notes: "*Required Reading:* [Notes on prerequisites](notes/prerequisite_notes.pdf)"
    - date: "Jan 22"
      topic: "Perfect Security"
      slides: "[PDF](slides/lec_1.pdf)"
      notes: "*Additional Reading:* Sections 2.1.1 and 2.1.2 from the [Boneh-Shoup Book](https://toc.cryptobook.us/)."
    - date: "Jan 27"
      topic: "Limitations of Perfect Security"
      slides: "[PDF](slides/lec_2.pdf)"
      notes: "*Additional Reading:* Section 2.1.3 from the [Boneh-Shoup Book](https://toc.cryptobook.us/)."
    - date: "Jan 29"
      topic: "Computational Security"
      slides: "[PDF](slides/lec_3.pdf)"
      notes: |
          *Additional Reading:*

          - [Chapter 2 of Intensive Intro to Crypto](https://intensecrypto.org/public/lec_02_computational-security.html)
          - Sections 2.2 and 2.3 from the [Boneh-Shoup Book](https://toc.cryptobook.us/).
    - date: "Feb 3"
      topic: "Pseudorandomness"
      slides: "[PDF](slides/lec_4.pdf)"
      notes: "*Additional Reading:* Sections 3.1 to 3.3 from the [Boneh-Shoup Book](https://toc.cryptobook.us/)."
    - date: "Feb 5"
      topic: "Pseudorandomness II"
      slides: "[PDF](slides/lec_5.pdf)"
      notes: "*Additional Reading:* Sections 3.4 to 3.12 from the [Boneh-Shoup Book](https://toc.cryptobook.us/)."
    - date: "Feb 10"
      topic: "Pseudorandomness II and Proof Techniques"
      slides: "[PDF](slides/lec_6.pdf)"
      notes: |
          *Additional Reading:* 

          - Sections 4.4, 4.6, and 4.8 from the [Boneh-Shoup Book](https://toc.cryptobook.us/) (ignore the block cipher sections).
          -  [Notes on pseudorandomness](notes/pseudorandomness_notes.pdf)
    - date: "Feb 12"
      topic: "Pseudorandomness III and Midterm Review"
      slides: "[PDF](slides/lec_7.pdf)"
      notes: |
        [Board Work Notes](notes/lec_7_board_work.pdf)
    - date: "Feb 19"
      topic: "Pseudorandomness IV and Encryption I"
      slides: "[PDF](slides/lec_8.pdf)"
      notes: |
          *Additional Reading:* Sections 5.1-5.4 from the [Boneh-Shoup Book](https://toc.cryptobook.us/), which go over constructing encryption schemes for messages of variable length.
